version: 2
jobs:
  build:
    working_directory: ~/likecoin-wordpress
    docker:
      - image: composer:1.6
    steps:
      - checkout
      - restore_cache:
          key: likecoin-wordpress-{{ .Environment.CACHE_UUID }}-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
      - run:
          name: Install phpcs
          command: composer install
      - run:
          name: Install wp php standard
          command: |
            git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git ./wpcs
            ./vendor/bin/phpcs --config-set installed_paths `pwd`/wpcs
      - run:
          name: Lint Test
          command: ./vendor/bin/phpcs likecoin --standard=WordPress-Extra --extensions=php
      - save_cache:
          key: likecoin-wordpress-{{ .Environment.CACHE_UUID }}-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
            - ./wpcs
